#!/usr/bin/env python

import re
import sys
import argh
from datetime import date
from getpass import getpass
from robobrowser import RoboBrowser


@argh.arg('-d', type=int, required=True, help='date')
@argh.arg('-m', type=int, help='month')
@argh.arg('-y', type=int, help='year')
@argh.arg('--hour', type=int, help='hour')
@argh.arg('--min', type=int, help='minutes')
@argh.arg('--location', help='location')
def main(d=None, m=None, hour="7", y=None, min="30", location="123 rue royale 1000 Bruxelles Belgique", title=None):
    robot = RoboBrowser(parser="html5lib")

    if m is None:
        m = date.today().month

    # we are in am/pm mode
    if hour > 12:
        hour -= 12
        ampm = 'PM'
    else:
        ampm = 'AM'

    robot.session.verify = False  # until letsencrypt our cert is self signed #yolo

    robot.open("https://neutrinet.be/index.php")

    previous_meeting = [x.text for x in robot.find_all('a', href=lambda x: x and 'Event:' in x) if re.match('^Meeting [0-9]+/[0-9]+$', x.text)][0]

    year, number = map(int, previous_meeting.split()[1].split("/"))

    if y is None:
        y = date.today().year

    if y < 2000:
        y += 2000

    if year != y:
        next_number = 1
    else:
        next_number = 1 + number

    next_meeting = "Meeting %i/%.2i" % (y, next_number)

    print "I'm about to create the event '%s' on %s:%s %s/%s/%s at '%s'" % (next_meeting if title is None else title, hour, min, d, m, year, location)

    if raw_input('Continue? [Y/n]: ') == 'n':
        sys.exit(0)

    robot.open("https://neutrinet.be/index.php?title=Special:UserLogin&returnto=Main+Page")

    form = robot.get_form(method="post")

    assert form is not None

    print "Login into mediawiki:"
    username = raw_input('Username: ')
    form['wpName'] = username
    form['wpPassword'] = getpass()

    robot.submit_form(form)

    # go to add event page
    robot.follow_link(robot.find_all('a', href='/index.php?title=Form:Event')[0])

    form = robot.get_form(action="/index.php?title=Special:FormStart")

    form["page_name"] = next_meeting if title is None else title

    robot.submit_form(form)

    # semantic form is bullshit and do a redirect in javascript
    destination = re.search('window.location="([^"]+)"', str(robot.parsed)).groups()[0]

    robot.open("https://neutrinet.be" + destination)

    form = robot.get_form("sfForm")

    form['Event[Date][day]'] = d
    form['Event[Date][month]'] = '%.2i' % m
    form['Event[Date][year]'] = y
    form['Event[Date][hour]'] = hour
    form['Event[Date][minute]'] = min
    form['Event[Date][ampm24h]'] = ampm
    form['Event[Lieu]'] = location
    form['Event[Organisateur]'] = username
    form['Event[Statut]'] = 'Ready'
    form['sf_free_text'] = ('https://pad.lqdn.fr/p/neutrinet-%.2i-%i' % (next_number, y)) if title is None else ''

    robot.submit_form(form, form.submit_fields["wpSave"])


if __name__ == '__main__':
    argh.dispatch_command(main)
